### ISSUE TITLE
Not working with rails 3.2

### ISSUE THREAD

**Issue by ajbraus** [ddollar/heroku-pg-transfer#12]
I have no password on my local database so I put in:

heroku pg:transfer --to "postgres://username@localhost/project-development"

and I get

Error:       undefined method `url' for #<Array:0x007fdd2a8e06c0> (NoMethodError)
    Backtrace:   /Users//.heroku/plugins/heroku-pg-transfer/init.rb:88:in`transfer_resolve'
                 /Users//.heroku/plugins/heroku-pg-transfer/init.rb:24:in `transfer'
                 /Users//.rvm/gems/ruby-1.9.3-p448/gems/heroku-2.28.12/lib/heroku/command.rb:178:in`run'
                 /Users//.rvm/gems/ruby-1.9.3-p448/gems/heroku-2.28.12/lib/heroku/cli.rb:25:in `start'
                 /Users//.rvm/gems/ruby-1.9.3-p448/gems/heroku-2.28.12/bin/heroku:16:in`<top (required)>'
                 /Users//.rvm/gems/ruby-1.9.3-p448/bin/heroku:23:in `load'
                 /Users//.rvm/gems/ruby-1.9.3-p448/bin/heroku:23:in`<main>'
                 /Users//.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
                 /Users//.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`<main>'

```
Command:     heroku pg:transfer --to postgres://bmb@localhost/bmb-development
Version:     heroku-gem/2.28.12 (x86_64-darwin11.4.2) ruby/1.9.3
```
