### ISSUE TITLE
Not working with Heroku 2.31.3

### ISSUE THREAD

**Issue by michrome** [ddollar/heroku-pg-transfer#3]
env DATABASE_URL=postgres://localhost/myappname_development heroku pg:transfer

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       undefined method `last' for #<Heroku::Helpers::HerokuPostgresql::Attachment:0x100a9d368> (NoMethodError)
Backtrace:   /Users/michael/.heroku/plugins/heroku-pg-transfer/init.rb:86:in `transfer_resolve'
             /Users/michael/.heroku/plugins/heroku-pg-transfer/init.rb:22:in `transfer'
             /Users/michael/.heroku/client/lib/heroku/command.rb:206:in `send'
             /Users/michael/.heroku/client/lib/heroku/command.rb:206:in `run'
             /Users/michael/.heroku/client/lib/heroku/cli.rb:28:in `start'
             /usr/bin/heroku:25

Command:     heroku pg:transfer
Plugins:     heroku-accounts
             heroku-pg-transfer

Version:     heroku-toolbelt/2.31.3 (universal-darwin12.0) ruby/1.8.7
```
